version: '3'

services:
  ToolServerManager:
    image: tool-server-manager:0.2
    build:
      context: ./
      dockerfile: dockerfiles/ToolServerManager/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
     DB_HOST: db
     DB_PORT: 27017
     DB_USERNAME: ${DB_USERNAME}
     DB_PASSWORD: ${DB_PASSWORD}
     DB_COLLECTION: ${DB_COLLECTION}
    depends_on:
      - db
    command: ["--workers","4","-t","600"]

  # This will create a test node that will never be used by XAgent
  ToolServerNode:
    image: tool-server-node:0.2
    build:
      context: ./
      dockerfile: dockerfiles/ToolServerNode/Dockerfile
    entrypoint: /bin/sh -c 'echo "Build complete. Exiting..." && exit 0'
    command: echo "Build complete. Exiting..."

  ToolServerMonitor:
    image: tool-server-monitor:0.1
    build:
      context: ./
      dockerfile: dockerfiles/ToolServerMonitor/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
     DB_HOST: db
     DB_PORT: 27017
     DB_USERNAME: ${DB_USERNAME}
     DB_PASSWORD: ${DB_PASSWORD}
     DB_COLLECTION: ${DB_COLLECTION}
    depends_on:
      - db

  db:
    image: mongo
    restart: always
    volumes:
      - xagentmongodb:/data/db
    environment:
     MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
     MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    logging:
      driver: "none"

  XAgentServer:
    image: xagent-server:0.3
    restart: always
    build:
      context: ./
      dockerfile: dockerfiles/XAgentServer/Dockerfile
    container_name: XAgent-Server
    env_file:
      - .env
    environment:
      - TOOLSERVER_URL=http://ToolServerManager:8080
      - MYSQL_DB_URL=mysql+pymysql://root:xagent@xagent-mysql:3306/xagent
      - REDIS_HOST=xagent-redis
    volumes:
      - ./assets:/app/assets:ro
    ports:
      - "5173:5173"
      - "8090:8090"
    depends_on:
      xagent-mysql:
        condition: service_healthy
      xagent-redis:
        condition: service_healthy

  xagent-mysql:
    image: mysql
    command:
      # - --default-authentication-plugin=caching_sha2_password
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: xagent
    ports:
      - "3306:3306"
    volumes:
      - ./XAgentServer/database/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin","ping", "-h", "localhost" ]
      interval: 20s
      timeout: 10s
      retries: 10

  xagent-redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass xagent
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3



volumes:
  xagentmongodb:

networks:
  default:
    name: tool-server-network
    driver: bridge
